language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "OscarDocker-React"
  env: "Oscardockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-906161076658"
  bucket_path: "OscarDocker-React"
  on:
    branch: master

branches:
  only:
    - master
